version: "3.3"

networks:
  public:
    external: true

services:
  webshell:
    container_name: webshell
    hostname: webshell
    image: kesokaj/webshell:latest
    volumes:
    - ./data:/home
    environment:
    - TZ=Europe/Stockholm
    - SHELL_USER=<CHANGE ME>
    - SHELL_PASSWORD=<CHANGE ME>
    volumes:
    - ./home:/home
    expose:
    - 80 #gui
    - 8080 #web-preview
    - 22 #ssh-port --> 2233
    networks:
    - public
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    # HTTP
    - "traefik.http.routers.webshell.entrypoints=websecure"
    - "traefik.http.routers.webshell.rule=Host(`webshell.app.spgo.se`)"
    - "traefik.http.routers.webshell.tls.certresolver=letsencrypt"
    - "traefik.http.services.webshell.loadbalancer.server.port=80"
    - "traefik.http.middlewares.webshell-auth.basicauth.users=ostsim:$$apr1$$PDTm63In$$gbaRZOxkznLbdsB2gW4gg."
    - "traefik.http.routers.webshell.middlewares=webshell-auth"
    - "traefik.http.routers.webshell.service=webshell"
    # HTTP - PREVIEW
    - "traefik.http.routers.webshellview.entrypoints=websecure"
    - "traefik.http.routers.webshellview.rule=Host(`webshell-view.app.spgo.se`)"
    - "traefik.http.routers.webshellview.tls.certresolver=letsencrypt"
    - "traefik.http.services.webshellview.loadbalancer.server.port=8080"
    - "traefik.http.routers.webshellview.service=webshellview"
    # TCP
    - "traefik.tcp.routers.webshell.entrypoints=sshd"
    - "traefik.tcp.routers.webshell.rule=HostSNI(`*`)"
    - "traefik.tcp.routers.webshell.service=webshell"
    - "traefik.tcp.services.webshell.loadbalancer.server.port=22"
