version: "3.3"
services:
  webshell:
    container_name: webshell
    hostname: webshell
    image: ghcr.io/kesokaj/webshell:v1
    privileged: true
    volumes:
    - ./home:/home
    environment:
    - TZ=Europe/Stockholm
    - SHELL_USER=user
    - SHELL_PASSWORD=user
    ports:
    - "8080:8080"
    restart: unless-stopped
