name: publish
on: [push]
jobs:
webshell::
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the webshell Docker image
run: |
       docker build . --tag ghcr.io/kesokaj/webshell:latest
       docker run ghcr.io/kesokaj/webshell:latest
       docker push ghcr.io/kesokaj/webshell:latest
